"""Serializable Taige HF backend caches for cluster continuation sweeps."""

from __future__ import annotations

from dataclasses import dataclass, field as dataclass_field
import hashlib
import json
import os
from pathlib import Path
import re
import tempfile
from typing import Any

import numpy as np
from pydantic import BaseModel, ConfigDict, Field

from chiral_dw.config import (
    ContinuumFiniteQParams,
    ContinuumGridParams,
    ContinuumInteractionParams,
    ContinuumModelParams,
)
from chiral_dw.continuum.hf import ContinuumHFBackend, ValleySectorExchange
from chiral_dw.continuum.hf_bands import hf_band_chern_table
from chiral_dw.continuum.models import (
    ContinuumActiveSpace,
    ContinuumBundle,
    ContinuumHFDiagnostics,
    ContinuumHFResult,
    DensityVertices,
    MomentumGrid,
)

TAIGE_BACKEND_CACHE_SCHEMA = "taige_backend_cache_v1"


class TaigeBackendCacheManifest(BaseModel):
    """Metadata for one loadable Taige HF backend cache."""

    model_config = ConfigDict(frozen=True, populate_by_name=True)

    cache_schema: str = Field(default=TAIGE_BACKEND_CACHE_SCHEMA, alias="schema")
    cache_hash: str
    path: str
    signature: dict[str, Any]
    has_vp_references: bool = False
    vertex_layout: str
    exchange_representation: str
    density_vertex_retention: str
    n_blocks: int = Field(ge=1)
    dim: int = Field(ge=1)
    n_active: int = Field(ge=1)
    vp_hf_chern_rows: tuple[dict[str, Any], ...] = Field(default_factory=tuple)
    vp_hf_chern_columns: dict[str, float] = Field(default_factory=dict)


@dataclass(frozen=True)
class LoadedTaigeBackendCache:
    """Loaded backend cache plus optional VP references."""

    bundle: ContinuumBundle
    manifest: TaigeBackendCacheManifest
    vp_plus: ContinuumHFResult | None = None
    vp_minus: ContinuumHFResult | None = None
    vp_hf_chern_rows: tuple[dict[str, Any], ...] = ()
    vp_hf_chern_columns: dict[str, float] = dataclass_field(default_factory=dict)

    @property
    def has_vp_references(self) -> bool:
        return self.vp_plus is not None and self.vp_minus is not None


def _json_hash(payload: dict[str, Any]) -> str:
    text = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(text.encode()).hexdigest()[:16]


def _safe_column_fragment(value: str) -> str:
    text = str(value).strip().lower()
    text = text.replace("+", "plus").replace("-", "minus").replace("=", "_")
    text = re.sub(r"[^a-z0-9]+", "_", text)
    return text.strip("_") or "unnamed"


def hf_chern_columns_from_rows(rows: list[dict[str, Any]] | tuple[dict[str, Any], ...]) -> dict[str, float]:
    """Return flattened HF Chern columns using sweep-table naming."""

    columns: dict[str, float] = {}
    for row in rows:
        key = (
            "chern_hf_"
            f"{_safe_column_fragment(str(row['reference']))}_"
            f"band_{int(row['band'])}"
        )
        columns[key] = float(row["chern"])
    return columns


def vp_hf_chern_rows(
    active: ContinuumActiveSpace,
    *,
    vp_plus: ContinuumHFResult | None,
    vp_minus: ContinuumHFResult | None,
) -> tuple[dict[str, Any], ...]:
    """Return compact VP+ and VP- HF Chern rows for a cached Taige point."""

    rows: list[dict[str, Any]] = []
    if vp_plus is not None:
        rows.extend(
            row.model_dump(mode="json")
            for row in hf_band_chern_table(active, vp_plus.H_hf, reference="VP+")
        )
    if vp_minus is not None:
        rows.extend(
            row.model_dump(mode="json")
            for row in hf_band_chern_table(active, vp_minus.H_hf, reference="VP-")
        )
    return tuple(rows)


def taige_backend_cache_signature(
    *,
    model: ContinuumModelParams,
    grid: ContinuumGridParams,
    interaction: ContinuumInteractionParams,
    finite_q: ContinuumFiniteQParams | None = None,
) -> dict[str, Any]:
    """Return the seed-independent cache signature for one Taige HF backend."""

    fq = finite_q or ContinuumFiniteQParams()
    return {
        "schema": TAIGE_BACKEND_CACHE_SCHEMA,
        "model": model.model_dump(mode="json"),
        "grid": grid.model_dump(mode="json"),
        "interaction": interaction.model_dump(mode="json"),
        "finite_q": fq.model_dump(mode="json"),
        "basis_convention": "hole active basis, Kprime generated by T-prime gauge",
        "density_vertex_convention": "projected hole density vertices in active frame",
        "backend_contents": (
            "active basis, h0, retained Hartree channels, exchange representation, "
            "and optional VP references"
        ),
    }


def taige_backend_cache_hash(signature: dict[str, Any]) -> str:
    """Return the stable cache digest for a signature."""

    return _json_hash(signature)


def taige_backend_cache_path(cache_root: str | Path, signature: dict[str, Any]) -> Path:
    """Return the default path for one cache signature."""

    return Path(cache_root).expanduser().resolve() / taige_backend_cache_hash(signature) / "backend_cache.npz"


def _tuple_array(values: tuple[tuple[int, int], ...]) -> np.ndarray:
    return np.asarray(values, dtype=int).reshape(-1, 2)


def _tuple_from_array(values: np.ndarray) -> tuple[tuple[int, int], ...]:
    arr = np.asarray(values, dtype=int).reshape(-1, 2)
    return tuple((int(row[0]), int(row[1])) for row in arr)


def _optional_array_payload(value: np.ndarray | None) -> np.ndarray:
    if value is None:
        return np.asarray([], dtype=float)
    return np.asarray(value)


def _optional_array(data: Any, key: str, *, present: bool) -> np.ndarray | None:
    if not present:
        return None
    return np.asarray(data[key])


def _channels_to_json(channels: Any) -> list[list[float]]:
    return [[int(iq), int(ig), float(v)] for iq, ig, v in channels]


def _channels_from_json(rows: list[list[float]]) -> list[tuple[int, int, float]]:
    return [(int(row[0]), int(row[1]), float(row[2])) for row in rows]


def _lookup_to_json(lookup: dict[tuple[int, int], tuple[int, int, float]]) -> list[list[float]]:
    return [
        [int(old_iq), int(old_ig), int(new_iq), int(new_ig), float(v)]
        for (old_iq, old_ig), (new_iq, new_ig, v) in sorted(lookup.items())
    ]


def _lookup_from_json(rows: list[list[float]]) -> dict[tuple[int, int], tuple[int, int, float]]:
    return {
        (int(row[0]), int(row[1])): (int(row[2]), int(row[3]), float(row[4]))
        for row in rows
    }


def _hf_result_arrays(prefix: str, result: ContinuumHFResult) -> dict[str, np.ndarray]:
    return {
        f"{prefix}_P": np.asarray(result.P, dtype=complex),
        f"{prefix}_H_hf": np.asarray(result.H_hf, dtype=complex),
    }


def _hf_result_metadata(result: ContinuumHFResult, *, max_iter: int | None = None) -> dict[str, Any]:
    return {
        "energy": float(result.energy),
        "converged": bool(result.converged),
        "n_iter": int(result.n_iter),
        "max_iter": None if max_iter is None else int(max_iter),
        "diagnostics": result.diagnostics.model_dump(mode="json"),
        "seed": result.seed,
        "constraint_name": result.constraint_name,
    }


def _write_npz_compressed_atomically(path: Path, arrays: dict[str, np.ndarray]) -> None:
    """Write an NPZ beside the target, then atomically replace the final path."""

    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as fh:
            tmp_path = Path(fh.name)
            np.savez_compressed(fh, **arrays)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp_path, path)
        tmp_path = None
    finally:
        if tmp_path is not None:
            try:
                tmp_path.unlink()
            except FileNotFoundError:
                pass


def _load_hf_result(prefix: str, data: Any, metadata: dict[str, Any]) -> ContinuumHFResult | None:
    ref_meta = metadata.get("hf_references", {}).get(prefix)
    if ref_meta is None:
        return None
    diagnostics = ContinuumHFDiagnostics.model_validate(ref_meta["diagnostics"])
    return ContinuumHFResult(
        P=np.asarray(data[f"{prefix}_P"], dtype=complex),
        H_hf=np.asarray(data[f"{prefix}_H_hf"], dtype=complex),
        energy=float(ref_meta["energy"]),
        converged=bool(ref_meta["converged"]),
        n_iter=int(ref_meta["n_iter"]),
        diagnostics=diagnostics,
        seed=str(ref_meta.get("seed") or ""),
        constraint_name=ref_meta.get("constraint_name"),
    )


def save_taige_backend_cache(
    path: str | Path,
    *,
    bundle: ContinuumBundle,
    signature: dict[str, Any],
    vp_plus: ContinuumHFResult | None = None,
    vp_minus: ContinuumHFResult | None = None,
    vp_reference_max_iter: int | None = None,
    compute_vp_chern: bool = True,
) -> TaigeBackendCacheManifest:
    """Write a loadable backend cache without raw full form-factor retention."""

    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    active = bundle.active
    backend = bundle.backend
    vertices = backend.vertices
    cache_hash = taige_backend_cache_hash(signature)
    has_vp = vp_plus is not None and vp_minus is not None
    chern_rows = (
        vp_hf_chern_rows(active, vp_plus=vp_plus, vp_minus=vp_minus)
        if compute_vp_chern and has_vp
        else ()
    )
    chern_columns = hf_chern_columns_from_rows(chern_rows)
    metadata = {
        "schema": TAIGE_BACKEND_CACHE_SCHEMA,
        "cache_hash": cache_hash,
        "signature": signature,
        "model": bundle.params.model_dump(mode="json"),
        "grid": {"n_k": int(bundle.grid.n_k)},
        "finite_q": bundle.finite_q.model_dump(mode="json"),
        "interaction": bundle.interaction.model_dump(mode="json"),
        "active": {
            "n_active": int(active.n_active),
            "shell": [list(item) for item in active.shell],
            "n_plane_waves": int(active.n_plane_waves),
            "finite_q_enabled": bool(active.finite_q_enabled),
            "q_coord": None if active.q_coord is None else [int(x) for x in active.q_coord],
            "half_shift_coord": None
            if active.half_shift_coord is None
            else [int(x) for x in active.half_shift_coord],
        },
        "backend": {
            "vertex_layout": str(backend.vertex_layout),
            "exchange_representation": str(backend.exchange_representation),
            "density_vertex_retention": str(bundle.interaction.density_vertex_retention),
            "hartree_channels": _channels_to_json(backend.hartree_channels),
            "full_hartree_channels": _channels_to_json(backend.full_hartree_channels),
            "hartree_channel_lookup": _lookup_to_json(backend._hartree_channel_lookup),
            "has_channel_in_disk": vertices.channel_in_disk is not None,
            "has_q_vectors_nm_inv": vertices.q_vectors_nm_inv is not None,
            "has_q_norm_nm_inv": vertices.q_norm_nm_inv is not None,
            "has_v_q": vertices.v_q is not None,
        },
        "hf_references": {},
        "vp_hf_chern_rows": list(chern_rows),
        "vp_hf_chern_columns": chern_columns,
    }
    arrays: dict[str, np.ndarray] = {
        "metadata_json": np.asarray(json.dumps(metadata, sort_keys=True)),
        "h0": np.asarray(active.h0, dtype=complex),
        "hole_energies": np.asarray(active.hole_energies, dtype=float),
        "band_vectors": np.asarray(active.band_vectors, dtype=complex),
        "electron_energies": _optional_array_payload(active.electron_energies),
        "electron_vectors": _optional_array_payload(active.electron_vectors),
        "source_index": _optional_array_payload(active.source_index),
        "source_shift": _optional_array_payload(active.source_shift),
        "vertices_q_shifts": _tuple_array(vertices.q_shifts),
        "vertices_g_channels": _tuple_array(vertices.g_channels),
        "vertices_target_minus_q": np.asarray(vertices.target_minus_q, dtype=int),
        "vertices_q_is_zero": np.asarray(vertices.q_is_zero, dtype=bool),
        "vertices_v_over_a": np.asarray(vertices.v_over_a, dtype=float),
        "vertices_channel_in_disk": _optional_array_payload(vertices.channel_in_disk),
        "vertices_q_vectors_nm_inv": _optional_array_payload(vertices.q_vectors_nm_inv),
        "vertices_q_norm_nm_inv": _optional_array_payload(vertices.q_norm_nm_inv),
        "vertices_v_q": _optional_array_payload(vertices.v_q),
        "backend_target_minus_q": np.asarray(backend.target_minus_q, dtype=int),
        "backend_q_is_zero": np.asarray(backend.q_is_zero, dtype=bool),
        "backend_v_over_a": np.asarray(backend.v_over_a, dtype=float),
        "backend_lambda_blocks": np.asarray(backend.lambda_blocks, dtype=complex),
        "backend_lambda_compact": _optional_array_payload(backend.lambda_compact),
        "backend_tVE": _optional_array_payload(backend.tVE),
        "backend_exchange_sectors": _optional_array_payload(
            None if backend.valley_sector_exchange is None else backend.valley_sector_exchange.sectors
        ),
    }
    if vp_plus is not None:
        arrays.update(_hf_result_arrays("vp_plus", vp_plus))
        metadata["hf_references"]["vp_plus"] = _hf_result_metadata(
            vp_plus,
            max_iter=vp_reference_max_iter,
        )
    if vp_minus is not None:
        arrays.update(_hf_result_arrays("vp_minus", vp_minus))
        metadata["hf_references"]["vp_minus"] = _hf_result_metadata(
            vp_minus,
            max_iter=vp_reference_max_iter,
        )
    arrays["metadata_json"] = np.asarray(json.dumps(metadata, sort_keys=True))
    _write_npz_compressed_atomically(out, arrays)
    return TaigeBackendCacheManifest(
        cache_hash=cache_hash,
        path=str(out),
        signature=signature,
        has_vp_references=has_vp,
        vertex_layout=str(backend.vertex_layout),
        exchange_representation=str(backend.exchange_representation),
        density_vertex_retention=str(bundle.interaction.density_vertex_retention),
        n_blocks=int(backend.n_blocks),
        dim=int(backend.dim),
        n_active=int(backend.n_active),
        vp_hf_chern_rows=chern_rows,
        vp_hf_chern_columns=chern_columns,
    )


def load_taige_backend_cache(path: str | Path) -> LoadedTaigeBackendCache:
    """Load a Taige backend cache and reconstruct a usable ContinuumBundle."""

    cache_path = Path(path)
    with np.load(cache_path, allow_pickle=False) as data:
        metadata = json.loads(str(np.asarray(data["metadata_json"]).item()))
        if metadata.get("schema") != TAIGE_BACKEND_CACHE_SCHEMA:
            raise ValueError(f"{cache_path} is not a {TAIGE_BACKEND_CACHE_SCHEMA} cache")
        model = ContinuumModelParams.model_validate(metadata["model"])
        grid_params = ContinuumGridParams.model_validate(metadata["grid"])
        interaction = ContinuumInteractionParams.model_validate(metadata["interaction"])
        finite_q = ContinuumFiniteQParams.model_validate(metadata["finite_q"])
        grid = MomentumGrid(grid_params.n_k)
        active_meta = metadata["active"]
        active = ContinuumActiveSpace(
            grid=grid,
            n_active=int(active_meta["n_active"]),
            h0=np.asarray(data["h0"], dtype=complex),
            hole_energies=np.asarray(data["hole_energies"], dtype=float),
            band_vectors=np.asarray(data["band_vectors"], dtype=complex),
            model=model,
            shell=_tuple_from_array(np.asarray(active_meta["shell"], dtype=int).reshape(-1, 2)),
            n_plane_waves=int(active_meta["n_plane_waves"]),
            electron_energies=(
                None
                if np.asarray(data["electron_energies"]).size == 0
                else np.asarray(data["electron_energies"], dtype=float)
            ),
            electron_vectors=(
                None
                if np.asarray(data["electron_vectors"]).size == 0
                else np.asarray(data["electron_vectors"], dtype=complex)
            ),
            source_index=(
                None
                if np.asarray(data["source_index"]).size == 0
                else np.asarray(data["source_index"], dtype=int)
            ),
            source_shift=(
                None
                if np.asarray(data["source_shift"]).size == 0
                else np.asarray(data["source_shift"], dtype=int)
            ),
            finite_q_enabled=bool(active_meta["finite_q_enabled"]),
            q_coord=(
                None
                if active_meta.get("q_coord") is None
                else tuple(int(x) for x in active_meta["q_coord"])
            ),
            half_shift_coord=(
                None
                if active_meta.get("half_shift_coord") is None
                else tuple(int(x) for x in active_meta["half_shift_coord"])
            ),
        )
        backend_meta = metadata["backend"]
        vertex_layout = str(backend_meta["vertex_layout"])
        n_blocks = int(active.grid.size)
        dim = int(active.dim)
        vertices = DensityVertices(
            q_shifts=_tuple_from_array(data["vertices_q_shifts"]),
            target_minus_q=np.asarray(data["vertices_target_minus_q"], dtype=int),
            q_is_zero=np.asarray(data["vertices_q_is_zero"], dtype=bool),
            lambda_blocks=np.zeros((0, 0, n_blocks, dim, dim), dtype=complex),
            v_over_a=np.asarray(data["vertices_v_over_a"], dtype=float),
            g_channels=_tuple_from_array(data["vertices_g_channels"]),
            vertex_layout=vertex_layout,  # type: ignore[arg-type]
            lambda_compact=(
                np.zeros((0, 0, n_blocks, 2, active.n_active, active.n_active), dtype=complex)
                if vertex_layout == "valley_compact"
                else None
            ),
            channel_in_disk=_optional_array(
                data,
                "vertices_channel_in_disk",
                present=bool(backend_meta["has_channel_in_disk"]),
            ),
            q_vectors_nm_inv=_optional_array(
                data,
                "vertices_q_vectors_nm_inv",
                present=bool(backend_meta["has_q_vectors_nm_inv"]),
            ),
            q_norm_nm_inv=_optional_array(
                data,
                "vertices_q_norm_nm_inv",
                present=bool(backend_meta["has_q_norm_nm_inv"]),
            ),
            v_q=_optional_array(data, "vertices_v_q", present=bool(backend_meta["has_v_q"])),
        )
        backend = ContinuumHFBackend.__new__(ContinuumHFBackend)
        backend.h0 = np.asarray(data["h0"], dtype=complex)
        backend.n_blocks = n_blocks
        backend.dim = dim
        backend.n_total = n_blocks * dim
        backend.vertices = vertices
        backend.interaction = interaction
        backend.vertex_layout = vertex_layout
        backend.lambda_blocks = np.asarray(data["backend_lambda_blocks"], dtype=complex)
        compact = np.asarray(data["backend_lambda_compact"])
        backend.lambda_compact = None if compact.size == 0 else np.asarray(compact, dtype=complex)
        backend.n_active = int(active.n_active)
        backend.target_minus_q = np.asarray(data["backend_target_minus_q"], dtype=int)
        backend.q_is_zero = np.asarray(data["backend_q_is_zero"], dtype=bool)
        backend.v_over_a = np.asarray(data["backend_v_over_a"], dtype=float)
        backend.n_q = int(backend.v_over_a.shape[0])
        backend.n_g = int(backend.v_over_a.shape[1]) if backend.v_over_a.ndim == 2 else 0
        backend.p_ref = np.zeros_like(backend.h0, dtype=complex)
        backend.hartree_channels = _channels_from_json(backend_meta["hartree_channels"])
        backend.full_hartree_channels = tuple(
            _channels_from_json(backend_meta["full_hartree_channels"])
        )
        backend._hartree_channel_lookup = _lookup_from_json(
            backend_meta["hartree_channel_lookup"]
        )
        backend.exchange_representation = str(backend_meta["exchange_representation"])
        backend.tVE = None
        backend.valley_sector_exchange = None
        if backend.exchange_representation == "valley_sector":
            sectors = np.asarray(data["backend_exchange_sectors"], dtype=complex)
            if sectors.size == 0:
                raise ValueError("cache is missing valley-sector exchange data")
            backend.valley_sector_exchange = ValleySectorExchange(
                sectors=sectors,
                n_blocks=n_blocks,
                n_active=int(active.n_active),
            )
        else:
            tve = np.asarray(data["backend_tVE"], dtype=complex)
            if tve.size == 0:
                raise ValueError("cache is missing dense exchange data")
            backend.tVE = tve
        bundle = ContinuumBundle(
            grid=grid,
            active=active,
            vertices=vertices,
            backend=backend,
            params=model,
            interaction=interaction,
            finite_q=finite_q,
            bands=None,
            geometry=None,
            form_factors=None,
        )
        vp_plus = _load_hf_result("vp_plus", data, metadata)
        vp_minus = _load_hf_result("vp_minus", data, metadata)
        chern_rows = tuple(dict(row) for row in metadata.get("vp_hf_chern_rows", []))
        chern_columns = {
            str(key): float(value)
            for key, value in metadata.get("vp_hf_chern_columns", {}).items()
        }
    manifest = TaigeBackendCacheManifest(
        cache_hash=str(metadata["cache_hash"]),
        path=str(cache_path),
        signature=dict(metadata["signature"]),
        has_vp_references=vp_plus is not None and vp_minus is not None,
        vertex_layout=str(metadata["backend"]["vertex_layout"]),
        exchange_representation=str(metadata["backend"]["exchange_representation"]),
        density_vertex_retention=str(metadata["backend"]["density_vertex_retention"]),
        n_blocks=int(bundle.backend.n_blocks),
        dim=int(bundle.backend.dim),
        n_active=int(bundle.backend.n_active),
        vp_hf_chern_rows=chern_rows,
        vp_hf_chern_columns=chern_columns,
    )
    return LoadedTaigeBackendCache(
        bundle=bundle,
        manifest=manifest,
        vp_plus=vp_plus,
        vp_minus=vp_minus,
        vp_hf_chern_rows=chern_rows,
        vp_hf_chern_columns=chern_columns,
    )


__all__ = [
    "LoadedTaigeBackendCache",
    "TAIGE_BACKEND_CACHE_SCHEMA",
    "TaigeBackendCacheManifest",
    "hf_chern_columns_from_rows",
    "load_taige_backend_cache",
    "save_taige_backend_cache",
    "taige_backend_cache_hash",
    "taige_backend_cache_path",
    "taige_backend_cache_signature",
    "vp_hf_chern_rows",
]
